// Code generated by "stringer -type=AudioFormatEnum"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AudioNone-0]
	_ = x[AudioDefault-1]
	_ = x[AudioMP3-2]
	_ = x[AudioM4A-3]
	_ = x[AudioWAV-4]
	_ = x[AudioULAW-5]
}

const _AudioFormatEnum_name = "AudioNoneAudioDefaultAudioMP3AudioM4AAudioWAVAudioULAW"

var _AudioFormatEnum_index = [...]uint8{0, 9, 21, 29, 37, 45, 54}

func (i AudioFormatEnum) String() string {
	if i < 0 || i >= AudioFormatEnum(len(_AudioFormatEnum_index)-1) {
		return "AudioFormatEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AudioFormatEnum_name[_AudioFormatEnum_index[i]:_AudioFormatEnum_index[i+1]]
}
