// Code generated by "stringer -type=InterpretAsType,InterpretAsDetailType -linecomment=true"; DO NOT EDIT.

package ssml

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InterpretAsTypeUnset-0]
	_ = x[InterpretAsTypeCharacters-1]
}

const _InterpretAsType_name = "unsetcharacters"

var _InterpretAsType_index = [...]uint8{0, 5, 15}

func (i InterpretAsType) String() string {
	if i < 0 || i >= InterpretAsType(len(_InterpretAsType_index)-1) {
		return "InterpretAsType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InterpretAsType_name[_InterpretAsType_index[i]:_InterpretAsType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InterpretAsDetailTypeUnset-0]
	_ = x[InterpretAsDetailTypeReadSymbols-1]
}

const _InterpretAsDetailType_name = "unsetread-symbols"

var _InterpretAsDetailType_index = [...]uint8{0, 5, 17}

func (i InterpretAsDetailType) String() string {
	if i < 0 || i >= InterpretAsDetailType(len(_InterpretAsDetailType_index)-1) {
		return "InterpretAsDetailType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InterpretAsDetailType_name[_InterpretAsDetailType_index[i]:_InterpretAsDetailType_index[i+1]]
}
