// Code generated by "stringer -type=NEREnum"; DO NOT EDIT.

package synthesizer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NERRegular-0]
	_ = x[NERSingleLetter-1]
	_ = x[NERGreekLetters-2]
	_ = x[NERReadableSymbol-3]
	_ = x[NERReadableAllSymbol-4]
}

const _NEREnum_name = "NERRegularNERSingleLetterNERGreekLettersNERReadableSymbolNERReadableAllSymbol"

var _NEREnum_index = [...]uint8{0, 10, 25, 40, 57, 77}

func (i NEREnum) String() string {
	if i < 0 || i >= NEREnum(len(_NEREnum_index)-1) {
		return "NEREnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NEREnum_name[_NEREnum_index[i]:_NEREnum_index[i+1]]
}
