port: 8000 
maxLogDataSize: 100
options:
  output:
    defaultFormat: mp3 
    # metadata:
    #   - copyright=UAB Intelektika
    #   - description=encoded by UAB Intelektika 

# numberReplace:
#   url:  

# tagger:
#   url:   

validator:
  maxChars: 10000 

# abbreviator:
#   url:       

# accenter:
#   url: 

# transcriber:
#   url:  

acousticModel:
  url: http://localhost:8000/model 

# vocoder:
#   url:     

# audioConvert:
#   url:    

# filer:
#   dir: 

cache:
  duration: 20m
