port: 8000
maxLogDataSize: 1500

debug:
    port: 8080
allowCustom: true
options:
  output:
    defaultFormat: mp3 
    metadata:
      - copyright=UAB Intelektika
      - description=encoded by UAB Intelektika
    defaultVoice: astra 
    voices: 
      - default:astra
      - astra:astra.v04
      - laimis:laimis.v04
      - laimis:laimis.v01
      - lina:lina.v04b
      - vytautas:vytautas.v06b


acousticModel:
  url:
  hasVocoder: true

validator:
  maxChars: 2500

splitter:
  maxChars: 200

partRunner:
  workers: 5  

suffixLoader:
  path: /suffixes    
